### ISSUE TITLE
When does the dataset and toolkit available?

### ISSUE THREAD

**Issue by superkevingit** [got-10k/toolkit#1]
Sorry for bothering, after I read the paper in arXiv, I am really interested in this work. I would like to know how soon will this wonderful work accessible to the vision tracking community?

**Comment by got-10k** [comment]
Hi, @superkevingit, we are working on the releasing issues of GOT-10k, and the website, toolkits and full dataset will be available soon.

**Comment by superkevingit** [comment]
Thank you for your time, I am looking forward to it.
