### ISSUE TITLE
VOT 2017 dataset URL does not exist

### ISSUE THREAD

**Issue by jonathantompson** [got-10k/toolkit#15]
vot.py line 112: http://data.votchallenge.net/vot2017/vot2017.zip <-- Returns 404.

**Comment by huanglianghua** [comment]
Fixed and add support for VOT2019. Please use `pip install --upgrade git+https://github.com/got-10k/toolkit.git@master` to access the new version (will be integrated into `pip` package in a near future).

**Comment by jonathantompson** [comment]
thanks.
