### ISSUE TITLE
assert len(img_files) == len(anno) error

### ISSUE THREAD

**Issue by tangjiasheng** [got-10k/toolkit#18]
Hi, I encountered some wired errors.
1st, when I unzip the files from BaiduYun, I only got 335 archives  that doesn't match the numbers in list.txt file. 
Then I create a new list file with my 335 folders and continue my training, the error `assert len(img_files) == len(anno)` in got10k.py, line 66 came out.
Can anyone help me?Thanks.

**Comment by tangjiasheng** [comment]
I think it is caused by something wrong with BaiduYun's source or my operation: cat *.zip > train_data.zip.

**Comment by ShihuaiXu** [comment]
have you find the solution? I met the same error
