### ISSUE TITLE
Can't download got-10k data

### ISSUE THREAD

**Issue by wulongjian** [got-10k/toolkit#41]
hello, I write my email(wulongjian@stu.ouc.edu.cn) in [http://got-10k.aitestunion.com/downloads_dataset/full_data](http://got-10k.aitestunion.com/downloads_dataset/full_data), but i don't get the response, Could you send a  download link to my email : wulongjian@stu.ouc.edu.cn?

**Comment by huanglianghua** [comment]
@wulongjian Hi, the link has been sent to you. Please check it.

**Comment by wulongjian** [comment]
get it, thanks.

**Comment by abhijeeetkumar** [comment]
hi, can you also send me the link for dataset. my email address is amk7371@psu.edu. I wrote an email and also raised a request from website, but no link yet :(
