### ISSUE TITLE
Can't download got-10k

### ISSUE THREAD

**Issue by lingqing97** [got-10k/toolkit#51]
When I try to download the GOT-10K from the [website Downloads - GOT-10k](http://got-10k.aitestunion.com/downloads), I  have not receive the dataset links in my email even now.
Can anyone share me the dataset links? Thanks!

**Comment by burnmyletters** [comment]
same here.
 requesting the dataset, but no link received

**Comment by huanglianghua** [comment]
@lingqing97 @burnmyletters Sorry for the bug. This bug was fixed very early, so I'll close the issue.
