### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by dengyang1** [got-10k/toolkit#6]
groundTruth's four numbers refer to tracked object center point coordinates, width and height?

**Comment by huanglianghua** [comment]
The 4 numbers refer to the left-top corner coordinates, width and height of a target:

```
<bb_left>, <bb_top>, <bb_width>, <bb_height>
```

All coordinate values are 1-based.

**Comment by dengyang1** [comment]
These four numbers refer to left-top or top-left? I want to crop bbox from image , I find that top-left is more accurate than left-top

**Comment by huanglianghua** [comment]
It's left-top, or `(x, y)`.

**Comment by dengyang1** [comment]
Thanks
