### ISSUE TITLE
数据集无法下载

### ISSUE THREAD

**Issue by yangkang779** [got-10k/toolkit#7]
你好，在项目主页上提交了下载的邮箱，可是没有收到下载数据集的链接，无法下载。这是邮箱，非常感谢。20172212247@nuist.edu.cn 。
用来测试的。

**Comment by huanglianghua** [comment]
Hi @yangkang779 ，这个邮箱在我这里提示拒收，已经补发，你可以查收。

**Comment by yangkang779** [comment]
好的谢谢，已经收到
