### ISSUE TITLE
Problem with the submission.

### ISSUE THREAD

**Issue by LuoXubo** [got-10k/toolkit#82]
Hi!

Thank you for your great work. However, I ran into some problems when I wanted to submit the compression results of the example method (SiamFC). When I click "Submit" again, the evaluation results are not generated as it should be, and the submitted files disappear.

Could you help solve this problem?

**Comment by Xuchen-Li** [comment]
We apologize for the inconvenience you experienced with the website.
We are currently attempting to check the process of submission.
Wait a moment, please.
Thanks for your attention and support for GOT-10k.

**Comment by Xuchen-Li** [comment]
I have tried my best to submit the results of SiamFC in the manner you described, but it seems there are no issues found.
Perhaps I have not fully grasped the issue you've described: 'When I click "Submit" again, the evaluation results are not generated as it should be, and the submitted files disappear.' To assist me in accurately diagnosing the problem, please send a detailed description of the issue to [lixuchen2024@ia.ac.cn](mailto:lixuchen2024@ia.ac.cn).

**Comment by Xuchen-Li** [comment]
After submitting the result, please wait for 1-2 minutes and then refresh the page to get the evaluation result. We do not recommend continuously clicking 'submit' to submit the results.

**Comment by LuoXubo** [comment]
> After submitting the result, please wait for 1-2 minutes and then refresh the page to get the evaluation result. We do not recommend continuously clicking 'submit' to submit the results.

Thanks for your help. I tried to submit the result again and it works! I'll close this issue :)
