### ISSUE TITLE
got10k server http request error

### ISSUE THREAD

**Issue by xiaolousun** [got-10k/toolkit#84]
Hi, I want to submit the got10k results to get the got-10k performance. But got this error "got-10k.aitestunion.com is currently unable to handle this request."
![QQ20240715-114750](https://github.com/user-attachments/assets/49dfec23-f147-42f7-90a5-98f8da437470)

**Comment by Xuchen-Li** [comment]
Hello, I can access the website normally. Perhaps you should check your network or VPN settings.
Thanks for your attention of GOT-10k.

**Comment by xiaolousun** [comment]
Thanks for your reply! I can also access the website normally. But when I submit the result (upload the results.zip and click the upload button), the error occurs. I try the different networks, but it does not work. Could you check the submission server?

**Comment by Xuchen-Li** [comment]
Hello, I submit the exemplar submission to GOT-10k server and all goes well.
You can email me at lixuchen2024@ia.ac.cn with your tracking results.
Thanks again.

**Comment by xiaolousun** [comment]
Thanks, I will try again. If it does not work, I will send the results to your email.
