### ISSUE TITLE
Grayscale images in OTB not converted

### ISSUE THREAD

**Issue by ZhouYzzz** [got-10k/toolkit#9]
https://github.com/got-10k/toolkit/blob/c2d213d2937af42dc27ce87841c476f83efc0f3b/got10k/trackers/__init__.py#L31

I think this line should be `image = image.convert('RGB')` to make sure that gray images are successfully converted. Otherwise the evaluation on OTB will fail.

**Comment by huanglianghua** [comment]
@ZhouYzzz Thanks for your feedback and also proposing a solution. We have fixed this bug in both GitHub and PyPI.
